name: miko
description: A new Flutter project.
publish_to: "none"
version: 1.5.3
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  csv: ^5.1.1
  shared_preferences: ^2.2.0
  flutter_easyloading: ^3.0.5
  get: ^4.6.5
  cached_network_image: ^3.2.3
  blur: ^3.1.0
  permission_handler: ^11.0.0
  url_launcher: ^6.1.1
  flutter_screenutil: ^5.8.4
  keframe: ^3.0.0
  get_it: ^7.6.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/story/
    - assets/photo/
